### ISSUE TITLE
Release of fakeredis 1.7.5 and up

### ISSUE THREAD

**Issue by acpaquette** [conda-forge/fakeredis-feedstock#21]
### Comment:

Hi all,

I was just curious on the state of releasing a 1.7.5 or up, version of fakeredis to conda-forge. A project that I am working on is running into issues in fakeredis that were handled in 1.7.5 and up. I saw that there are PRs open for the releases but they seem to have stalled over the past month. I am curious on the status of a potential release and was hoping that there is support to get a 1.7.5 or greater release out the door.

Thank you!

**Comment by cunla** [comment]
Hi, I took over the feedstock and  I'll start updating it.
